resolutions = [512, 720]
enable_ar_bucket = true
min_ar = 0.5
max_ar = 2.0
num_ar_buckets = 7
ar_buckets = [[512, 512], [448, 576], [1024, 1024]]
[[directory]]
path = '/home/ly/comfy/ComfyUI/custom_nodes/Diffusion_pipe_in_ComfyUI/input/test'
num_repeats = 5